Add controllers
VladimirTulsky/java-shareit pull request #1
Opened 2023-01-11 22:03 UTC by VladimirTulsky

2023-01-12 16:50 UTC, ErkinKasymaliev requested changes
Привет, хорошая работа!
Оставил комменты

2023-01-12 16:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
этот класс идентичен PostItemDto. Оставьте один

2023-01-12 16:50 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
над моделями валидация не нужна, она требуется для dto классов, поправьте где такое встречается

2023-01-12 18:56 UTC, VladimirTulsky commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
>  public class ItemDto {
удалил, отрефакторил код

2023-01-12 18:57 UTC, VladimirTulsky commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank
исправил, теперь валидация только в DTO, пришлось поправить используемые модели в нескольких местах

2023-01-13 06:07 UTC, ErkinKasymaliev approved these changes
Отлично, работа принята

2023-01-15 19:17 UTC, merged