Add bookings
VladimirTulsky/java-shareit pull request #3
Opened 2023-01-31 20:50 UTC by VladimirTulsky

2023-02-01 17:38 UTC, ErkinKasymaliev requested changes
привет, хороша работа!
Оставил пару комментов

2023-02-01 17:38 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .map(item -> setBookings(userId, item))
вот это мне нравится) каждый item будет делать еще несколько запросов - а это плохо. перепишите через join запрос - чтоб был один запрос и вы сразу его перемаппили

2023-02-01 17:38 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return setComments(setBookings(userId, item), itemId);
перепишите через join запрос - чтоб был один запрос и вы сразу его перемаппили

2023-02-01 20:48 UTC, VladimirTulsky commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      }
заменил на 1 метод, который запрашивает данные для всех вещей и обрабатывает в 3 запроса:
1. Находит 1 последнее бронирование для каждой вещи
2. Находит 1 ближайшее бронирование для каждой вещи
3. Подтягивает комментарии для всех запрошенных вещей

2023-02-02 06:39 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      }
ок, так тоже сойдет

2023-02-02 06:41 UTC, ErkinKasymaliev approved these changes
работа принята

2023-02-02 16:49 UTC, merged